### ISSUE TITLE
SSL error for Perl/Mojolicious Apps on a Raspberry Pi 4

### ISSUE THREAD

**Issue by bislink** [mojolicious/mojo#1997]
* Mojolicious version: 9.28
* Perl version: 5.32.1
* Operating system: Raspberry Pi 4 (8 GB RAM)

### Steps to reproduce the behavior
Open `https://spanel.gnani.xyz:44042` in a browser, I get error `ERR_CONNECTION_RESET`

### Expected behavior
Should load without error just like `https://spanel.gnani.xyz` served by Apache2

### Actual behavior
`wget --spider https://spanel.gnani.xyz:44042` gives the following error: 

```
GnuTLS: The TLS connection was non-properly terminated. 
Unable to establish SSL connection.
```
but the same certificate work ok for Apache2 : `https://spanel.gnani.xyz`

Certificate for Mojo App:

```
hypnotoad:
  listen:
    - 'http://*:44040'
    - 'https://*:44042?cert=certs/spanel.gnani.xyz/cert.pem&key=certs/spanel.gnani.xyz/privkey.pem'
  workers: 10
```
